[package]
name = "rhai-evm"
version = "0.1.1"
edition = "2024"
description = "Rhai plugin providing EVM token denomination helpers and primitive type conversions"
license = "MIT"
repository = "https://github.com/isSerge/rhai-evm"
authors = ["Serge Kovbasiuk <isserge@protonmail.com>"]
keywords = ["rhai", "evm", "alloy", "web3", "crypto"]
categories = ["api-bindings", "cryptography"]

[dependencies]
alloy-primitives = "1.3.0"
num-bigint = "0.4.5"
num-traits = "0.2.19"
rhai = {"version" = "1.22.2", features = ["decimal"]}
rust_decimal = { version = "1.37.2", features = ["maths"] }

[dev-dependencies]
rhai-bigint = "0.1.6"

[features]
default = []
sync = ["rhai/sync", "rhai-bigint/sync"]
